# ----
# Site

title: Software Research LLC
email: info@srllc.org
description: >- # this means to ignore newlines until "baseurl:"
    Software Research LLC has written software for the U.S. Department of
    Health and Human Services, the U.S. Office of the Director of National
    Intelligence, and the U.S. National Institute of Justice.  We specialize
    in machine learning, application programming, and custom software solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.srllc.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: none
github_username:  software-research-llc

# Build settings
#theme: hydra
#plugins:
#  - jekyll-feed

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /logo-dropshadow.png
author: Software Research LLC
email:
# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
#  - jekyll-archives
  - jekyll-sitemap
  #- jekyll-seo-tag
#  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - github

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
